name: Backend CI/CD

on:
  push:
    branches: [ "fix/backend.yml" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Spring Boot App
      run: ./gradlew build -x test -x spotlessJavaCheck

    - name: Setup SSH Key (base64 decode)
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY_B64 }}" | base64 -d > key.pem
        chmod 400 key.pem

    - name: Ensure backend directory exists on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@43.202.247.79 "mkdir -p /home/ubuntu/backend"
        
    - name: Upload JAR to EC2 with temp name and rename to app.jar
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no build/libs/*.jar ubuntu@43.202.247.79:/home/ubuntu/backend/temp.jar
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@43.202.247.79 "
          if [ -d /home/ubuntu/backend/app.jar ]; then
            rm -rf /home/ubuntu/backend/app.jar
          fi
          mv /home/ubuntu/backend/temp.jar /home/ubuntu/backend/app.jar
        "
        
    - name: Upload application.yml to EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no src/main/resources/application.yml ubuntu@43.202.247.79:/home/ubuntu/backend/

    - name: SSH & Restart Spring Boot App
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@43.202.247.79 << 'EOF'
        cd /home/ubuntu/backend

        # 종료할 프로세스 찾고 종료
        PID=$(ps -ef | grep 'java -jar app.jar' | grep -v grep | awk '{print $2}')
        if [ -n "$PID" ]; then
          kill "$PID"
          sleep 2
        fi

        # 백그라운드로 재실행
        nohup java -jar app.jar \
          --spring.config.location=file:/home/ubuntu/backend/application.yml \
          > app.log 2>&1 &
        EOF
